{% set name = "lintegrate" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://test-files.pythonhosted.org/packages/e7/eb/67e627eeaf05d5496859773e6799dd36d4a42a2837589e0abf2d394836ba/lintegrate-0.1.4.tar.gz
  sha256: af1473d0110c16b0e03a1fffe14184d54c0794213635e689e96b512f02ad38a9

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - gsl
    - numpy
    - python
    - pip
  run:
    - gsl
    - numpy
    - python

test:
  imports:
    - lintegrate

about:
  home: http://github.com/mattpitkin/lintegrate
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Python functions implementing numerical integration of functions in log-space.'
  dev_url: https://github.com/mattpitkin/lintegrate
  description: |
    lintegrate provides Python functions for numerical integration of functions
    in log-space. This is useful for functions that have a very large dynamic
    range, or intrinsically would include very large or small numbers, and
    therefore it is more practical to work with the natural logarithm of the
    function. In these cases it is useful to also stay within log-space when
    integrating the function, which is what this package enables.

    The functions provided by lintegrate are equivalent to, and based on,
    several numerical integration routines provided within the GNU Scientific
    Library (GSL).

extra:
  recipe-maintainers:
    - mattpitkin
