{% set name = "lintegrate" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: https://github.com/mattpitkin/lintegrate.git

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py27]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - gsl
    - numpy
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - gsl
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - lintegrate
  requires:
    - pytest
  commands:
    - pytest

about:
  home: http://github.com/mattpitkin/lintegrate
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python functions implementing numerical integration of functions in log-space.
  dev_url: https://github.com/mattpitkin/lintegrate
  description: |
    lintegrate provides Python functions for numerical integration of functions
    in log-space. This is useful for functions that have a very large dynamic
    range, or intrinsically would include very large or small numbers, and
    therefore it is more practical to work with the natural logarithm of the
    function. In these cases it is useful to also stay within log-space when
    integrating the function, which is what this package enables.

    The functions provided by lintegrate are equivalent to, and based on,
    several numerical integration routines provided within the GNU Scientific
    Library (GSL).

extra:
  recipe-maintainers:
    - mattpitkin
