{% set name = "lintegrate" %}
{% set version = "0.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3f2569ffe4364a86495baad870300723af73bc8c6373443a6c23e8e410aac848
  patches:
    # see https://github.com/duncanmmacleod/lintegrate/commits/conda-patches
    - 0001-pyproject.toml-remove-oldest-known-numpy.patch
    - 0002-setup.py-use-gsl-config-libs-without-cblas.patch

build:
  error_overdepending: true
  error_overlinking: true
  ignore_run_exports:
    - numpy
    - vs2015_runtime  # [win]
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    # extras for cross-compiling
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
  host:
    - cython
    - gsl
    - numpy
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - {{ pin_compatible('gsl') }}
    - {{ pin_compatible('numpy') }}
    - python

test:
  requires:
    - pip
    - pytest
  source_files:
    - test
  commands:
    # check requirements
    - python -m pip check
    # run unit tests
    - python -m pytest test -v -ra

about:
  home: http://github.com/mattpitkin/lintegrate
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python functions implementing numerical integration of functions in log-space.
  dev_url: https://github.com/mattpitkin/lintegrate.git
  description: |
    lintegrate provides Python functions for numerical integration of functions
    in log-space. This is useful for functions that have a very large dynamic
    range, or intrinsically would include very large or small numbers, and
    therefore it is more practical to work with the natural logarithm of the
    function. In these cases it is useful to also stay within log-space when
    integrating the function, which is what this package enables.

    The functions provided by lintegrate are equivalent to, and based on,
    several numerical integration routines provided within the GNU Scientific
    Library (GSL).

extra:
  recipe-maintainers:
    - mattpitkin
