travis:
  secure:
    BINSTAR_TOKEN: PdbDU8V+AZpN4dlvT3OdeCpM6ASE7Qt/fZ83F0BX9k+0O+iCwsNxVW5OtXJok9nEyVubXsj1b8gupex6gDvDYCccq/KAecxxdG9XdqRpzJhyPzpdYweu+Vxi6bS2bwvRyslBIzU32JqFjZUy28w0jtKyPD7YLW55dDGhD0SYJoLgqG9jGg+nEQPUMHhkAj+eQyZoKeK/zjAWTr+7cQWi+wPMu0Jwg2yJmaMnZRd4QrmYlj4i1fXgwi+W/+2aaB6JK5Nrw+hqgt2Sktrd8SlblhhEarNKCUc4nReodwfKWg+oIwlGFrT039MD0FQJ8Q0gefKoWNvJacFupmt4sq1NHisZChIkz9LR6G8Bq1JezW2AjpU6YYRmZxyrjos6NPPN/AFONZ3F8rSFT960ufOvyaF1wT+dYUXHNOfI1RrqQxeUbeqJfppnCbgznnh3SMgjlooL4QTi8GC0Ln/z4QYXTNqvpxSx+GPEFM7IOAB3jBOCHZyMEeR0FYEH8dDs+UCcIAzGcHBAt9cy21MB48k+SPQi/legD1kWRzyv3E4vNKevqoccYlKnTAVjSzIWM43h3le+351YtTOrZ5g6eqk+q/i1I/1OO9Ow4V0mY/NI9QxooO9MKPPS2xTnahATY9aXSif8QYd/IutUu6vCPovrL6j8T9RNQtZ4kE2NXVkh2QI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
